"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CUSTOMER_RETURN_FIELDS_PARAMETER = exports.ORDER_ONDEMAND_COLUMNS = exports.FLATTEN_ITEMS_PARAMETER = exports.ORDER_ITEM_FIELDS_PARAMETER = exports.ORDER_RETURN_FIELDS_PARAMETER = exports.PRODUCT_ONDEMAND_COLUMNS = exports.PRODUCT_RETURN_FIELDS_PARAMETER = exports.UPDATE_PRODUCT_ADDITIONAL_FIELDS_PARAMETER = exports.PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPDATE = exports.PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPDATE = exports.ORDER_ID_FIELD_PARAMETER_ACKNOWLEDGE = exports.INCLUDE_CUSTOM_FIELDS_PARAMETER = exports.IMAGE_ID_FIELD_PARAMETER = exports.IMAGE_TYPE_ID_PARAMETER = exports.FILE_PATH_TEMPLATE_PARAMETER = exports.IMAGE_URL_FIELD_PARAMETER = exports.PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPLOAD = exports.PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPLOAD = exports.INSERT_PRODUCT_ADDITIONAL_FIELDS_PARAMETER = exports.PRODUCT_NAME_FIELD_PARAMETER_INSERT = exports.PRODUCT_CODE_FIELD_PARAMETER_INSERT = exports.INVENTORY_ADJUSTMENT_PARAMETER = exports.RETURN_ID_FIELD_PARAMETER = exports.UPDATE_SHIPMENTS_ADDITIONAL_FIELDS_PARAMETER = exports.SHIPMENT_ID_FIELD_PARAMETER = exports.SHIPMENT_RETURN_FIELDS_PARAMETER = exports.CREATE_SHIPMENT_FIELD_PARAMETER = exports.CREATE_RETURN_FIELD_PARAMETER = exports.LINE_ID_FIELD_PARAMETER_SHIPMENT = exports.ORDER_ID_FIELD_PARAMETER_SHIPMENT = exports.LINE_ID_FIELD_PARAMETER = exports.ORDER_ID_FIELD_PARAMETER = exports.THRESHOLD_FIELD_PARAMETER = exports.INVENTORY_FIELD_PARAMETER = exports.PRODUCT_IDENTIFIER_FIELD_PARAMETER_REPORT = exports.PRODUCT_IDENTIFIER_TYPE_PARAMETER_REPORT = exports.ADJUSTMENT_FIELD_PARAMETER = exports.PRODUCT_IDENTIFIER_FIELD_PARAMETER_ADJUST = exports.PRODUCT_IDENTIFIER_TYPE_PARAMETER_ADJUST = exports.QUEUE_CODE_PARAMETER = exports.QUEUE_FILTER_PARAMETER = exports.OFFSET_PARAMETER = exports.BATCH_SIZE_PARAMETER = exports.COUNT_PARAMETER = exports.STORE_CODE_PARAMETER = exports.OPERATION_PARAMETER = void 0;
var common_1 = require("./common");
Object.defineProperty(exports, "OPERATION_PARAMETER", { enumerable: true, get: function () { return common_1.OPERATION_PARAMETER; } });
Object.defineProperty(exports, "STORE_CODE_PARAMETER", { enumerable: true, get: function () { return common_1.STORE_CODE_PARAMETER; } });
Object.defineProperty(exports, "COUNT_PARAMETER", { enumerable: true, get: function () { return common_1.COUNT_PARAMETER; } });
Object.defineProperty(exports, "BATCH_SIZE_PARAMETER", { enumerable: true, get: function () { return common_1.BATCH_SIZE_PARAMETER; } });
Object.defineProperty(exports, "OFFSET_PARAMETER", { enumerable: true, get: function () { return common_1.OFFSET_PARAMETER; } });
Object.defineProperty(exports, "QUEUE_FILTER_PARAMETER", { enumerable: true, get: function () { return common_1.QUEUE_FILTER_PARAMETER; } });
Object.defineProperty(exports, "QUEUE_CODE_PARAMETER", { enumerable: true, get: function () { return common_1.QUEUE_CODE_PARAMETER; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_TYPE_PARAMETER_ADJUST", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_TYPE_PARAMETER_ADJUST; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_FIELD_PARAMETER_ADJUST", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_FIELD_PARAMETER_ADJUST; } });
Object.defineProperty(exports, "ADJUSTMENT_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.ADJUSTMENT_FIELD_PARAMETER; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_TYPE_PARAMETER_REPORT", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_TYPE_PARAMETER_REPORT; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_FIELD_PARAMETER_REPORT", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_FIELD_PARAMETER_REPORT; } });
Object.defineProperty(exports, "INVENTORY_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.INVENTORY_FIELD_PARAMETER; } });
Object.defineProperty(exports, "THRESHOLD_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.THRESHOLD_FIELD_PARAMETER; } });
Object.defineProperty(exports, "ORDER_ID_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.ORDER_ID_FIELD_PARAMETER; } });
Object.defineProperty(exports, "LINE_ID_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.LINE_ID_FIELD_PARAMETER; } });
Object.defineProperty(exports, "ORDER_ID_FIELD_PARAMETER_SHIPMENT", { enumerable: true, get: function () { return common_1.ORDER_ID_FIELD_PARAMETER_SHIPMENT; } });
Object.defineProperty(exports, "LINE_ID_FIELD_PARAMETER_SHIPMENT", { enumerable: true, get: function () { return common_1.LINE_ID_FIELD_PARAMETER_SHIPMENT; } });
Object.defineProperty(exports, "CREATE_RETURN_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.CREATE_RETURN_FIELD_PARAMETER; } });
Object.defineProperty(exports, "CREATE_SHIPMENT_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.CREATE_SHIPMENT_FIELD_PARAMETER; } });
Object.defineProperty(exports, "SHIPMENT_RETURN_FIELDS_PARAMETER", { enumerable: true, get: function () { return common_1.SHIPMENT_RETURN_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "SHIPMENT_ID_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.SHIPMENT_ID_FIELD_PARAMETER; } });
Object.defineProperty(exports, "UPDATE_SHIPMENTS_ADDITIONAL_FIELDS_PARAMETER", { enumerable: true, get: function () { return common_1.UPDATE_SHIPMENTS_ADDITIONAL_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "RETURN_ID_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.RETURN_ID_FIELD_PARAMETER; } });
Object.defineProperty(exports, "INVENTORY_ADJUSTMENT_PARAMETER", { enumerable: true, get: function () { return common_1.INVENTORY_ADJUSTMENT_PARAMETER; } });
Object.defineProperty(exports, "PRODUCT_CODE_FIELD_PARAMETER_INSERT", { enumerable: true, get: function () { return common_1.PRODUCT_CODE_FIELD_PARAMETER_INSERT; } });
Object.defineProperty(exports, "PRODUCT_NAME_FIELD_PARAMETER_INSERT", { enumerable: true, get: function () { return common_1.PRODUCT_NAME_FIELD_PARAMETER_INSERT; } });
Object.defineProperty(exports, "INSERT_PRODUCT_ADDITIONAL_FIELDS_PARAMETER", { enumerable: true, get: function () { return common_1.INSERT_PRODUCT_ADDITIONAL_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPLOAD", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPLOAD; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPLOAD", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPLOAD; } });
Object.defineProperty(exports, "IMAGE_URL_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.IMAGE_URL_FIELD_PARAMETER; } });
Object.defineProperty(exports, "FILE_PATH_TEMPLATE_PARAMETER", { enumerable: true, get: function () { return common_1.FILE_PATH_TEMPLATE_PARAMETER; } });
Object.defineProperty(exports, "IMAGE_TYPE_ID_PARAMETER", { enumerable: true, get: function () { return common_1.IMAGE_TYPE_ID_PARAMETER; } });
Object.defineProperty(exports, "IMAGE_ID_FIELD_PARAMETER", { enumerable: true, get: function () { return common_1.IMAGE_ID_FIELD_PARAMETER; } });
Object.defineProperty(exports, "INCLUDE_CUSTOM_FIELDS_PARAMETER", { enumerable: true, get: function () { return common_1.INCLUDE_CUSTOM_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "ORDER_ID_FIELD_PARAMETER_ACKNOWLEDGE", { enumerable: true, get: function () { return common_1.ORDER_ID_FIELD_PARAMETER_ACKNOWLEDGE; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPDATE", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_FIELD_PARAMETER_UPDATE; } });
Object.defineProperty(exports, "PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPDATE", { enumerable: true, get: function () { return common_1.PRODUCT_IDENTIFIER_TYPE_PARAMETER_UPDATE; } });
Object.defineProperty(exports, "UPDATE_PRODUCT_ADDITIONAL_FIELDS_PARAMETER", { enumerable: true, get: function () { return common_1.UPDATE_PRODUCT_ADDITIONAL_FIELDS_PARAMETER; } });
var productFields_1 = require("./productFields");
Object.defineProperty(exports, "PRODUCT_RETURN_FIELDS_PARAMETER", { enumerable: true, get: function () { return productFields_1.PRODUCT_RETURN_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "PRODUCT_ONDEMAND_COLUMNS", { enumerable: true, get: function () { return productFields_1.PRODUCT_ONDEMAND_COLUMNS; } });
var orderFields_1 = require("./orderFields");
Object.defineProperty(exports, "ORDER_RETURN_FIELDS_PARAMETER", { enumerable: true, get: function () { return orderFields_1.ORDER_RETURN_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "ORDER_ITEM_FIELDS_PARAMETER", { enumerable: true, get: function () { return orderFields_1.ORDER_ITEM_FIELDS_PARAMETER; } });
Object.defineProperty(exports, "FLATTEN_ITEMS_PARAMETER", { enumerable: true, get: function () { return orderFields_1.FLATTEN_ITEMS_PARAMETER; } });
Object.defineProperty(exports, "ORDER_ONDEMAND_COLUMNS", { enumerable: true, get: function () { return orderFields_1.ORDER_ONDEMAND_COLUMNS; } });
var customerFields_1 = require("./customerFields");
Object.defineProperty(exports, "CUSTOMER_RETURN_FIELDS_PARAMETER", { enumerable: true, get: function () { return customerFields_1.CUSTOMER_RETURN_FIELDS_PARAMETER; } });
//# sourceMappingURL=index.js.map